### ISSUE TITLE
Value names of my API don't correspond with the app

### ISSUE THREAD

**Issue by christhedj** [ChristianGr1974/de.grewenig.httpenergymeter#1]
Hi  -
I'm not an expert on APIs, but a friend of mine who actually works with smart meters confirms that the values required to set up the app don't match those in my provider (Octopus UK) API. Could you help please? Happy to send over the information in a private message.

**Comment by ChristianGr1974** [comment]
Hi,
can you please provide some more info's? The current implementation requires the field `id` to identify the meter in your homey setup. Also there is no authentication going on.

**Comment by christhedj** [comment]
Hi,
I've attached the details of the API provided by the company.

**Comment by ChristianGr1974** [comment]
Hi,
I cannot find any attachments. Can you please describe the problem in detail? Which fields don't match, or which fields are missing?
